server:
  port: 8081
  servlet:
    encoding:
      force-response: true

# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 각자 PC에 만들어놓은 Database이름을 써야함.
    url: jdbc:mysql://localhost:3306/db_member?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # mysql에 생성한 사용자 계정 정보를 써야함.
    username: user_jssa
    password: 1234
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  security:
    user:
      name: jssa
      password: 1234
    oauth2:
      client:
        registration:
          #naver registration
          naver:
            client-name: naver
            client-id: SLeTTfhsEYCGuE_dVJJ4
            client-secret: 1i9L26jns7
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
          #google registration
          google:
            client-name: google
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email
          #kakao registration
          kakao:
            client-name: kakao
            client-id: b4f76bbf0abeacb0deb048cbb15f10e0
            client-secret: BCE1JE5tdGCDGDPPiXFgEnEenHa9xOGG
            scope: profile_nickname, account_email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
          #facebook registration
          facebook:
            client-name: facebook
            client-id: 875122917130764
            client-secret: db88a990bcd67ba1b994dfe29b378b5c
            redirect-uri: http://localhost:8080/login/oauth2/code/facebook
            authorization-grant-type: authorization_code
            scope: email,public_profile
          provider:
            #naver provider
            naver:
              authorization-uri: https://nid.naver.com/oauth2.0/authorize
              token-uri: https://nid.naver.com/oauth2.0/token
              user-info-uri: https://openapi.naver.com/v1/nid/me
              user-name-attribute: response
            #kakao provider
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id